### PR TITLE
Draft: Add config to `TaskInstance` context

### LINKED ISSUE #698: Expose "meta" model config dictionary on `TaskInstance`
I'm working on integrating a PagerDuty setup with a Cosmos repo:

```python
def on_failure_callback(context: Context):
    summary = f"Airflow: DBT DAG {context.get('task_instance').dag_id} task failure"
    severity = "error"
    source = context.get("task_instance").task_id

    dedup_key = f"{context.get('task_instance').dag_id}-{context.get('task_instance').task_id}-{context.get('execution_date')}"

    pd_hook = PagerdutyEventsHook(pagerduty_events_conn_id="default_pagerduty")
    pd_hook.send_event(
        summary=summary,
        severity=severity,
        source=source,
        group=context.get("task_instance").dag_id,
        dedup_key=dedup_key,
        links=[{"href": context.get("task_instance").log_url, "text": "Airflow Log"}],
    )

```

This works well, but I'd love to be able to have metadata from a model like the `.meta.owner` field or even the tags attached to the `Context` object to be able to more intelligently route alerts within my callbacks. Is this possible to implement?

### PR DESCRIPTION
**Pull request by wseaton**
## Description

forwards context from the parsed model config object to the Airflow `TaskInstance` `Context` so it is available in callback functions

## Related Issue(s)

closes #698 

## Breaking Change?

not that I'm aware

## Checklist

- [x] I have made corresponding changes to the documentation (if required)
- [ ] I have added tests that prove my fix is effective or that my feature works

Would like guidance on where you'd like the tests for this, eg. mocked in the operators section or integration.

### CODE REVIEW

**Comment by wseaton** [comment]
Getting type check failures because of pre python 3.9 available type hint syntax that is being used, like `dict[str, Any]`. Do we want to fix that in other parts of the codebase?

**Comment by tatiana** [comment]
@wseaton, we find this very useful; please, if you have a chance, we'd love to see this work resumed!

For now, we're starting to close stale PRs - but please let us know if we can help you get this work to the finishing line.

Feel free to reopen or create a new PR.

**Comment by wseaton** [comment]
Thanks @tatiana, to be honest I actually forget why I needed this. Do you have any examples you can share publicly of how this would be useful? Perhaps I can pick it back up.

**Comment by linchun3** [comment]
Sorry for hijacking this, I have a use case for this feature and would like to contribute.

I have created a [draft PR](https://github.com/astronomer/astronomer-cosmos/pull/1044) to implement this feature :)

**Pull request closed without merging**
