### PR TITLE
Kubernetes on warning callback

### PR DESCRIPTION
**Pull request by david-mag**
## Description
In order to make `on_warning_callback` work with pod operators, we need to read the logs of the dbt test runs. This is done by making sure the pod is kept alive, and `on_success_callback` the log is read and anlayzed for warnings.
Afterwards the pod is cleaned up, based on the original settings from the user.

If `on_warning_callback` is not set, everything stays the way it always was.

I've tested the changes in my dev environment, but haven't added any new tests, since this would be something (I think) we would need to add integration tests for.

## Checklist

- [ ] I have made corresponding changes to the documentation (if required)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by tatiana — COMMENTED** [review]
Hey, @david-mag, this looks very good - it's great to have feature parity to use `on_warning_callback` on Kubernetes.

I'm apprehensive about the need for tests. An integration test would be ideal - and we could do that once #535 is completed.

In the meantime, how would you feel about adding some unit tests to the new methods and the class constructor?

**Comment by david-mag** [comment]
I've added some unit-tests that (I hope) will cover my additions to the `DbtTestKubernetesOperator`. I had to, however, add a condition to skip the test for airflow version 2.3, because there the `OnFinishAction` from `airflow.providers.cncf.kubernetes.utils.pod_manager` doesn't exist yet.

So using `on_warning_callback` will only be usable from airflow version 2.4 and up.

**Review by tatiana — APPROVED** [review]
@david-mag thanks for the contribution!

This will improve K8s users experience!

There will be scenarios when `OnFinishAction` won't be defined. If the user sets `on_warning_callback` and uses `ExecutionMode.KUBERNETES`,  `DbtTestKubernetesOperator` will only work if users use `apache-airflow-providers-cncf-kubernetes >= 7.4.0`. I believe this is a fine compromise, considering that before this PR `on_warning_callback` wasn't working for any version of the provider when users used  `ExecutionMode.KUBERNETES`.

**Comment by tatiana** [comment]
@david-mag This was released in 1.2.5 🎉 

* https://pypi.org/project/astronomer-cosmos/1.2.5
* https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.2.5

**Pull request merged**
