### PR TITLE
Return code or error ignores WarnErrorOptions

### PR DESCRIPTION
**Pull request by adammarples**
## Description

Ignore WarnErrorOptions string in stdout from dbt-core, do not treat it as a failure

## Related Issue(s)

Workaround for https://github.com/astronomer/astronomer-cosmos/issues/642

## Checklist

- [ ] I have made corresponding changes to the documentation (if required)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by tatiana — APPROVED** [review]
Thanks for the quick fix, @adammarples ! We're releasing this as part of Cosmos 1.2.5

**Comment by adammarples** [comment]
Awesome @tatiana thank you!

**Comment by tatiana** [comment]
@adammarples  This was released in 1.2.5 🎉 

* https://pypi.org/project/astronomer-cosmos/1.2.5
* https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.2.5

**Comment by tatiana** [comment]
@adammarples  This was released in 1.2.5 🎉 

* https://pypi.org/project/astronomer-cosmos/1.2.5
* https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.2.5

**Pull request merged**
