### PR TITLE
Make PostgresUserPasswordProfileMapping schema profile argument schem…

### PR DESCRIPTION
**Pull request by FouziaTariq**
## Description

Made PostgresUserPasswordProfileMapping schema profile argument optional

## Related Issue(s)

Closes: #675

### CODE REVIEW

**Review by tatiana — COMMENTED** [review]
Thank you very much, @FouziaTariq, for such a quick fix!
It's on the right track; this MR is just missing updating some tests, such as:
```
FAILED tests/profiles/postgres/test_pg_user_pass.py::test_connection_claiming - assert not True
```

**Comment by tatiana** [comment]
HI @FouziaTariq we're very close to merging this change. Please let us know if you'd like support on the tests.

**Comment by Fouzia-Tariq** [comment]
Hi @tatiana , I tried to fix them but that logic didn't work so I am not sure what's wrong with those integration tests & how to fix them.

**Review by tatiana — APPROVED** [review]
Thanks for fixing this, @FouziaTariq, we'll be releasing it as part of Cosmos 1.4

**Comment by tatiana** [comment]
@Fouzia-Tariq I fixed some minor issues with the tests - and I'm merging now. Thanks a lot for the patience and work on this - and apologies for the delay.

**Pull request merged**
