### PR TITLE
Refactor tests to be separated from  application code

### PR DESCRIPTION
**Pull request by tatiana**
Closes: #302

### CODE REVIEW

**Comment by jlaneve** [comment]
does this include the profiles changes too?

**Comment by tatiana** [comment]
@jlaneve just moved the new files as well! Please, have a look

**Comment by jlaneve** [comment]
@tatiana looks like tests are failing!

**Comment by jlaneve** [comment]
tests are failing bc of the datasets - digging into this now

**Review by jlaneve — APPROVED** [review]
thanks for making this change! this is great 🙂

**Pull request merged**
