### PR TITLE
Improve error logging in DbtLocalBaseOperator

### LINKED ISSUE #1003: Fix hard to read AirflowException error logs from dbt command
When a task fails, the produced error from dbt is logged in a single line which can be very long and hard to read, see here in code:

https://github.com/astronomer/astronomer-cosmos/blob/cb2a27a764ab8bfbf4e706678c3be2382da7747c/cosmos/operators/local.py#L184

this could be fixed with something like this instead

```
  def exception_handling(self, result: FullOutputSubprocessResult) -> None:
      if self.skip_exit_code is not None and result.exit_code == self.skip_exit_code:
          raise AirflowSkipException(f"dbt command returned exit code {self.skip_exit_code}. Skipping.")
      elif result.exit_code != 0:
          logger.error("\n".join(result.full_output))
          raise AirflowException(
              f"dbt command failed. The command returned a non-zero exit code {result.exit_code}. )
```

### PR DESCRIPTION
**Pull request by davidsteinar**
Improve error logging when the `dbt` command returns a non-zero exit code. Instead of raising an `AirflowException` with the full output, log the output using the logger and then raise the exception with a concise error message. This makes the dbt output more readable and not in a single line.

## Description
AirflowException logs message in a single line, can be very long. 
## Related Issue(s)

closes #1003 

## Breaking Change?

No

### CODE REVIEW

**Review by tatiana — COMMENTED** [review]
This looks much better, @davidsteinar , thanks a lot for the contribution!

Is there any chance we could add a test to make sure this improvement continues working as expected in the future?

**Comment by davidsteinar** [comment]
@tatiana  something like this?

```python
def test_handle_exception_subprocess():
    """
    Test the handle_exception_subprocess method of the DbtLocalBaseOperator class.
    """
    operator = DbtLocalBaseOperator(profile_config=None)
    result = FullOutputSubprocessResult(exit_code=1, output="test", full_output=["n" * n for n in range(1, 1000)])
    
    # Test when exit_code is non-zero
    with pytest.raises(AirflowException) as err_context:
        operator.handle_exception_subprocess(result)

    assert len(err_context.value) < 100 # Ensure the error message is not too long
```

**Comment by tatiana** [comment]
> @tatiana something like this?
> 
> ```python
> def test_handle_exception_subprocess():
>     """
>     Test the handle_exception_subprocess method of the DbtLocalBaseOperator class.
>     """
>     operator = DbtLocalBaseOperator(profile_config=None)
>     result = FullOutputSubprocessResult(exit_code=1, output="test", full_output=["n" * n for n in range(1, 1000)])
>     
>     # Test when exit_code is non-zero
>     with pytest.raises(AirflowException) as err_context:
>         operator.handle_exception_subprocess(result)
> 
>     assert len(err_context.value) < 100 # Ensure the error message is not too long
> ```

Hi @davidsteinar I think you're in the right path - thank you!

The one thing that could be improved is to use perhaps pytest `caplog` fixture ([more info](https://docs.pytest.org/en/7.1.x/how-to/logging.html#caplog-fixture)) and check the actual log message, confirming the new behaviour.

Example:
https://github.com/astronomer/astronomer-cosmos/blob/cb2a27a764ab8bfbf4e706678c3be2382da7747c/tests/test_cache.py#L76

**Comment by davidsteinar** [comment]
hi again @tatiana , better?
```python
def test_handle_exception_subprocess(caplog):
    """
    Test the handle_exception_subprocess method of the DbtLocalBaseOperator class.
    """
    operator = DbtLocalBaseOperator(profile_config=None)
    result = FullOutputSubprocessResult(exit_code=1, output="test", full_output=["n" * n for n in range(1, 1000)])
    
    caplog.set_level(logging.ERROR)
    # Test when exit_code is non-zero
    with pytest.raises(AirflowException) as err_context:
        operator.handle_exception_subprocess(result)
    assert len(str(err_context.value)) < 100 # Ensure the error message is not too long
    assert len(caplog.text) > 1000 # Ensure the log message is not truncated
```

**Review by pankajkoti — APPROVED** [review]

**Review by pankajkoti — COMMENTED** [review]
Looks like unfortunately there is a minor conflict with main in the file ``tests/operators/test_local.py`.` Could you please resolve the conflict and push the commit :) ?

**Comment by pankajkoti** [comment]
Thank you @davidsteinar for improving the exception and error logging. Appreciate the contribution and quick fixes 👏🏽 

PR looks good to me. I'm going ahead with the merge

cc: @tatiana

**Pull request merged**
