### PR TITLE
support static_index.html docs

### PR DESCRIPTION
**Pull request by dwreeves**
## Description

- Support `static_index.html` for dbt docs.
- Refactor remote filesystem access functions in anticipation of moving them out of `cosmos/plugins/__init__.py`. Refactoring is designed to make them behave a little more predictably, and to make them look a little more like Airflow 2.8+'s `ObjectStoragePath` class. Of course, this is far, far from complete.

## Related Issue(s)

- Main: #986
- Related: #927

## Breaking Change?

No breaking changes as far as the high level API is concerned.

## Checklist

- [ ] I have made corresponding changes to the documentation (if required)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by tatiana** [comment]
@dwreeves, thanks for these improvements!
I just noticed some tests are failing. Would you like us to review the code before the tests pass, or is this PR still in draft?

**Comment by dwreeves** [comment]
Sorry, for a long time I had issues with pre-commit due to a [strange error](https://stackoverflow.com/questions/76701323/trying-to-download-apache-airflow-with-pip-but-error-pops-up-when-building-whee). So for a while I'd never had pre-commit turned on for the repo.

I only recently fixed the issue and just forgot to `pre-commit install`. 😅 That is what is failing.

**Comment by dwreeves** [comment]
I added `packaging` to dependencies because it's explicitly used in one of the Cosmos modules.

Even though `apache-airflow` also depends on it, it's best practice to explicitly define what is depended on.

**Comment by dwreeves** [comment]
@tatiana Tests are stuck for some odd reason, but otherwise passing, so this is ready for review.

**Review by tatiana — COMMENTED** [review]
@dwreeves I think we're super close to get this change merged, do you by any chance have bandwith to improve a bit the test coverage? Codecov gave some feedback.
We'll release this in 1.5

**Comment by dwreeves** [comment]
@tatiana When are you intending on releasing 1.5?

**Review by tatiana — APPROVED** [review]
Thanks, @dwreeves , it looks great!

**Pull request merged**
