### PR TITLE
renaming on_warning_callback argument to on_test_warning_callback

### PR DESCRIPTION
**Pull request by CorsettiS**
## Description

 The arg **on_warning_callback** is renamed to **on_test_warning_callback**. This change is being done to prepare the groundwork for the **on_test_error_callback** argument that I plan to implement soon for the local execution mode and then expand both args to other execution modes.

## Breaking Change?

Yes.  **on_warning_callback** became **on_test_warning_callback**, therefore users should rename it accordingly 

## Checklist

- [X] I have made corresponding changes to the documentation (if required)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by jlaneve** [comment]
Thanks @CorsettiS! Two quick things:
- this is a breaking change, users who supply the `on_warning_callback` today will need to update their code to `on_test_warning_callback` (to be clear: I'm fine with the breaking change, just want to call this out for any users looking at this PR)
- mind fixing the [pre-commit checks](https://results.pre-commit.ci/run/github/577757880/1691093425.hkkSJSZ3QI-ECezowTtFkA)? once they're fixed, this looks good to me!

**Comment by CorsettiS** [comment]
> Thanks @CorsettiS! Two quick things:
> 
> * this is a breaking change, users who supply the `on_warning_callback` today will need to update their code to `on_test_warning_callback` (to be clear: I'm fine with the breaking change, just want to call this out for any users looking at this PR)
> * mind fixing the [pre-commit checks](https://results.pre-commit.ci/run/github/577757880/1691093425.hkkSJSZ3QI-ECezowTtFkA)? once they're fixed, this looks good to me!

@jlaneve thanks for the clarification ! just changed it !

**Review by tatiana — CHANGES_REQUESTED** [review]
Let's deprecate the previous parameter, having a deprecation warning. Since this is a breaking change, we should not release it in minor/micro releases.

**Comment by CorsettiS** [comment]
> [@tatiana](/tatiana)
> ** tatiana ** requested changes

I have done as requested. now everytime that on_warning_callback is called instead of on_test_warning_callback a logging.warn will pop up

**Comment by CorsettiS** [comment]
I have seen that some tests failed. I will have to take a look into that later, although recently I am busy with some personal projects. I will add updates here once I have more time

**Comment by CorsettiS** [comment]
I will close this PR for now and reopen it once I deploy the on_test_failure_callback method

**Pull request closed without merging**
