### PR TITLE
Add vertica profile with test

### PR DESCRIPTION
**Pull request by perttus**
## Description

Added Vertica profile with test

## Related Issue(s)

#538 

## Checklist

- [ ] I have made corresponding changes to the documentation (if required)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by tatiana — COMMENTED** [review]
Hi @perttus , this looks amazing, thank you very much for your contribution!
Is there any chance you could add a test to cover `mock_profile`?
We can release this as part of 1.2.0.

**Comment by tatiana** [comment]
Sorry, @perttus , we ended up postponing this release to 1.3. I just solved a conflict, and we'll merge the PR once the tests pass.

**Comment by perttus** [comment]
> Sorry, @perttus , we ended up postponing this release to 1.3. I just solved a conflict, and we'll merge the PR once the tests pass.

No worries, I'm glad to see it in 1.3 then 👍 
Thanks for resolving the conflict!

**Review by tatiana — APPROVED** [review]
Thank you very much for the contribution, @perttus !

**Comment by tatiana** [comment]
@perttus, this change is available in the 1.3.0a1 pre-release of Cosmos:
* https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.3.0a1
* https://pypi.org/project/astronomer-cosmos/1.3.0a1/

Thank you very much for your contribution!

**Pull request merged**
