### PR TITLE
Make GoogleCloudServiceAccountDictProfileMapping dataset profile argument optional

### LINKED ISSUE #837: Make GoogleCloudServiceAccountDictProfileMapping dataset profile argument optional
**Context**

Given the issue [here](https://github.com/astronomer/astronomer-cosmos/issues/675) and the discussion around it [in slack](https://apache-airflow.slack.com/archives/C059CC42E9W/p1700049843620749), it follows that it would not be too far off for other profile mapping classes (like GCP) to have their schema (dataset in GCP terms) arguments made optional. 

The configurations in dbt (profiles.yml, dbt_project.yml, model level configs etc.) are meant to provide the dataset. As such, me and my team's initial thoughts were to not provide any arguments here since usually we would rely on this being handled inside of dbt instead of it being hard coded at the DAG (orchestration) level.

**Solution**

I believe its possible modifying this line [here ](https://github.com/astronomer/astronomer-cosmos/blob/72690d31ba6822ae6df56f4d56f26196234c80b5/cosmos/profiles/bigquery/service_account_keyfile_dict.py#L25) and the associated code similarly to this issue [here](https://github.com/astronomer/astronomer-cosmos/issues/675) would be the right path.

Me and/or my colleague are happy to to attempt this modification if there are no objections to this proposed change. Please let us know, thanks

### PR DESCRIPTION
**Pull request by oliverrmaa**
## Description

This PR follows the methodology in https://github.com/astronomer/astronomer-cosmos/pull/683/ by modifying the GCP `GoogleCloudServiceAccountDictProfileMapping()` `profile_args` not require dataset as a required argument. 

## Related Issue(s)

Closes #837 

## Breaking Change?

Not to my knowledge.

## Checklist

- [x] I have made corresponding changes to the documentation (if required)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by oliverrmaa** [comment]
tagging @astro-cosmos-admins @tatiana for review, I wasn't able to tag anyone as reviewer since I don't have permissions so hopefully writing it as a comment is okay. Thank you

**Review by jbandoro — COMMENTED** [review]
Thanks for your contribution @olivermaa!

I didn't realize "dataset"/"schema" was not required for the profiles file. I've changed it before by overriding the `generate_schema_name` as described in the [docs](https://docs.getdbt.com/docs/build/custom-schemas) where it by default concatenates the default target schema with the custom one which we found annoying.

If the default target schema from the profiles file is null do you still have to change the `generate_schema_name` macro?

**Review by tatiana — COMMENTED** [review]
@oliverrmaa thank you very much for your contribution! Is there any chance you could address @jbandoro 's feedback? We may be able to add this as part of the 1.4.0 release later this week if you are.

**Comment by pankajastro** [comment]
Hey @oliverrmaa, Thanks for your contribution! Could you please rebase and respond to @jbandoro's feedback? we're excited to see this move forward.

**Comment by pankajastro** [comment]
Hi @oliverrmaa, I was wondering if you had a chance to read my previous comments. Are you still working on it, or would it be alright if I take it forward from here? Thank you!

**Comment by tatiana** [comment]
Since we consider this change very relevant, we ended up rebasing and addressing conflicts in a separate PR and adding @oliverrmaa as a co-author: #1017

**Pull request closed without merging**
