### PR TITLE
Add on_kill to DbtBaseOperator to recognize execution timeouts

### PR DESCRIPTION
**Pull request by pohek321**

### CODE REVIEW

**Comment by pohek321** [comment]
@jlaneve I think this is what our operator is missing. Have you ever developed one of these?

**Comment by jlaneve** [comment]
I haven't. Have you tested/does this work?

**Comment by pohek321** [comment]
> I haven't. Have you tested/does this work?

Spinning up a sandbox to try it out now. From the looks of it, this is [how the BashOperator is handling it](https://github.com/apache/airflow/blob/main/airflow/operators/bash.py#L201). [OSS docs](https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/models/baseoperator.html) are pretty vague on the subject.

**Comment by pohek321** [comment]
@jlaneve that was it! I put a 15-second execution_timeout on the operator to test and a 60-second `time.sleep` in the execution method so that I could test it - and after adding the `on_kill` it worked as expected.

**Review by jlaneve — APPROVED** [review]
nice! good find

**Pull request merged**
