### PR TITLE
Fix invalid argument (`full_refresh`) passed to DbtTestAwsEksOperator (and others)

### PR DESCRIPTION
**Pull request by johnhoran**
https://github.com/astronomer/astronomer-cosmos/pull/590/ added a fix to consume the kwargs `full_refresh_ignore` if it wasn't consumed by a higher class as it was preventing the use of test in the DbtTaskGroup if `full_refresh_ignore` was set.  The previous patch fixed this by consuming the variable for the `DbtLocalBaseOperator`, leaving a bug in kubernetes and docker operator.  Since `AbstractDbtBaseOperator` has been added as a base of `DbtDockerBaseOperator`, `DbtKubernetesBaseOperator` and `DbtLocalBaseOperator`, moving the code there will fix all three.

Fixes https://github.com/astronomer/astronomer-cosmos/issues/1062

### CODE REVIEW

**Comment by johnhoran** [comment]
https://github.com/astronomer/astronomer-cosmos/issues/1062

**Review by tatiana — COMMENTED** [review]
@johnhoran thank you very much for making this contribution!

Could you add a unittest that covers that scenario that stopped working - so we make sure we don't have any regressions in this area in future? Perhaps it could be on an EKS or K8s operator, since that's where the issue was first spotted.

Also, could you please update the PR description to include "Fixes #1062" or "Closes #1062", so when we merge the PR the related issue is closed automagically?

**Comment by johnhoran** [comment]
@tatiana sure, I've added a test.  My strategy there was to have an exception thrown after the kubernetes manifest is created and then examine the manifest to check the correct arguments are being passed to DBT.

**Comment by pankajkoti** [comment]
hi @johnhoran could you please rebase the PR. We just merged #1182 that should fix the breaking CI jobs.

**Comment by johnhoran** [comment]
Thanks @pankajkoti

**Review by tatiana — APPROVED** [review]
This looks great, @johnhoran , thank you very much for reporting and fixing the issue! We'll release this as part of Cosmos 1.7

**Pull request merged**
