### PR TITLE
Support Snowflake encrypted private key path

### LINKED ISSUE #607: Snowflake auth encrypted key path not supported
`astronomer-cosmos` is unable to map a snowflake connection with an encrypted private key **path**

To reproduce, use an Airflow connection to Snowflake with `extra.private_key_file` and `password` settings, for example:
```
AIRFLOW_CONN_SNOWFLAKE_TEST='{
  "conn_type": "snowflake",
  "login": "username",
  "password": "secret",
  "host": "https://ACCOUNT.snowflakecomputing.com",
  "schema": "public",
  "extra": {
    "region": "eu-central-1",
    "account": "ACCOUNT",
    "private_key_file": "/path/to/rsa_key.p8",
    "database": "test",
    "role": "system",
    "warehouse": "default"
  }
}'
```

### PR DESCRIPTION
**Pull request by ivanstillfront**
## Description

This adds support for Snowflake Airflow Connections with encrypted private key paths via `extra.private_key_file` and `password` configuration.

## Related Issue(s)

closes #607

## Breaking Change?

None

## Checklist

- [ x ] I have made corresponding changes to the documentation (if required)
- [ x ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by jlaneve — COMMENTED** [review]
thanks for opening this so quickly! love the direction this is headed - I wonder if there's a way to converge this new profile mapping with the existing `SnowflakePrivateKeyPemProfileMapping`, did you try that by chance? I haven't looked into it yet so it may not be possible, was just curious

**Comment by ivanstillfront** [comment]
> thanks for opening this so quickly! love the direction this is headed - I wonder if there's a way to converge this new profile mapping with the existing `SnowflakePrivateKeyPemProfileMapping`, did you try that by chance? I haven't looked into it yet so it may not be possible, was just curious

I did try this, the existing `SnowflakePrivateKeyPemProfileMapping` maps to `private_key_content` but I needed `private_key_path` (and passhprase) The mapping class became much more complicated when I tried to make it work for both scenarios. (Also because Airflow Snowlake connection re-purposes `password` for the key passphrase)

**Review by tatiana — APPROVED** [review]
Thanks for the contribution and addressing @jlaneve comments, @ivanstillfront ! We can merge this PR once the checks pass. We'll be releasing it as part of Cosmos 1.3.

**Comment by tatiana** [comment]
@ivanstillfront please, could you add tests covering these lines pointed out by codecov?

Screenshot 2023-10-19 at 14 29 29

Once this is done, we can merge this PR.

**Pull request merged**
