### PR TITLE
Add cancel on kill functionality

### PR DESCRIPTION
**Pull request by dwreeves**
In dbt, [a `SIGTERM` does not cancel any running queries](https://medium.com/@brianepohl/terminating-dbt-in-dagster-kubernetes-job-c53c3bc26012), but a `SIGINT` does. The `SubprocessHook()` does not have a `send_sigint()` method, so we can just copy+paste the source code for it and replace the `SIGTERM` with `SIGINT`.

### CODE REVIEW

**Review by jlaneve — APPROVED** [review]
nice, very good catch and thanks for the contribution!

**Comment by dwreeves** [comment]
@jlaneve Thanks for merging! I have experience integrating dbt and Airflow together and I want to use this integration (I hate managing my own), so I'll be keeping an eye on this project and add a few more things as I get time.

**Comment by jlaneve** [comment]
@dwreeves that would be awesome! Feel free to also open issues with things you think are missing - we can certainly help implement

**Comment by dwreeves** [comment]
Will do. I have at least one nontrivial feature I'd like to see and that will involve some discussion. I'll get to opening an issue hopefully in the next week.

**Pull request merged**
