### PR TITLE
Add more pre-commit checks

### PR DESCRIPTION
**Pull request by tatiana**
Most pre-commit checks required no or minor changes to the code/docs. If reviewers prefer, I can split the multiple commits of this PR into different PRs.

Benefits of each pre-commit check introduced:
1. `check-merge-conflict`: checks for files that contain merge conflict strings.
2. `debug-statements`: checks for debugger imports and py37+ `breakpoint()` calls in Python source.
3. `mixed-line-ending`: replaces or checks mixed line ending
4. `pretty-format-json`: sets a standard for formatting JSON files
5. `codespell`: checks for common misspellings in text files.
6. `rst-backticks`: detect common mistake of using single backticks when writing rst
9. `python-check-mock-methods`: prevent common mistakes of `assert mck.not_called()`, `assert mck.called_once_with(...)` and `mck.assert_called`.
11. `remove-crlf`: replace CRLF end-lines with LF ones before committing
14. `remove-tabs`: replace tabs with whitespaces before committing
16. `blacken-docs`: run `black` on Python code blocks in documentation files
https://pre-commit.com/hooks.html

This commit/PR also introduces some changes to the configuration, such as making sure Black and Ruff have the same line size limit.

MyPy is commented on and will be addressed in a separate PR since it found 235 errors in 29 files (checked 58 source files).

The only CI check that is failing due to coverage relates to pre-existing coverage issues and is unrelated to the type of change introduced in this PR.

### CODE REVIEW

**Review by jlaneve — COMMENTED** [review]
Can we justify adding each of these? Pre-commit on my machine now takes 7+ seconds, which feels quite long

**Comment by tatiana** [comment]
@jlaneve I added to the PR description the motivation for each check introduced.

I believe with time we should introduce more checks, which will help us have code quality and consistency.

Airflow pre-commit checks take even longer. I believe the benefits introduced are higher than the drawbacks - but I'm happy for you to suggest removals

**Comment by jlaneve** [comment]
Thank you, the description is super helpful! Couple notes:
- for `clrf` and `tabs`, can we keep just one of the forbid + remove? having them both seems redundant
- can we remove `isort` in favor of ruff?
- `check-merge-conflict` - do we need this? will nothing else fail if there are merge conflicts?

**Comment by jlaneve** [comment]
Also worth noting that `python-no-log-warn` isn't needed with Ruff: https://beta.ruff.rs/docs/rules/deprecated-log-warn/

**Comment by tatiana** [comment]
@jlaneve I addressed most of your feedback, thank you!

The only exception was:

> * check-merge-conflict - do we need this? will nothing else fail if there are merge conflicts?

Not necessarily. Configuration and documentation may not fail if there are merge conflicts.

**Review by jlaneve — APPROVED** [review]

**Pull request merged**
