### PR TITLE
[DOCS] Add scarf to readme and docs for website analytics

### PR DESCRIPTION
**Pull request by cmarteepants**
This adds a privacy notice and website analytics to the Cosmos readme and auto-generated docs. 

Note that while you cannot explicitly opt out of website analytics for the publicly hosted readme (and docs), Scarf respects browser DND. If that is set via the browser, telemetry for that user will not be sent to Scarf.

Scarf privacy policy: https://about.scarf.sh/privacy-policy
Astronomer privacy policy: https://www.astronomer.io/privacy/

### CODE REVIEW

**Comment by cmarteepants** [comment]
@pankajkoti or @tatiana - I'm going to need some help. I'm not sure why no changes were detected for the docs, and why it didn't successfully build. When I ran `hatch run docs:serve` locally, they compiled properly

**Comment by tatiana** [comment]
> @pankajkoti or @tatiana - I'm going to need some help. I'm not sure why no changes were detected for the docs, and why it didn't successfully build. When I ran `hatch run docs:serve` locally, they compiled properly

I believe the change worked and when we render the Restructured Text in Github, it also works:
https://github.com/astronomer/astronomer-cosmos/pull/1221/files?short_path=7b3ed02#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168f

The warning you're receiving is probably due to the Netlify configuration:
https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds

They are only used for validating the docs and do not affect our current docs deployment. Either we can do something about the Netlify config ^ or we can merge this without viewing changes in Netlify. I'm happy either way.

**Review by tatiana — APPROVED** [review]

**Comment by pankajkoti** [comment]
> I'm not sure why no changes were detected for the docs, and why it didn't successfully build. When I ran `hatch run docs:serve` locally, they compiled properly

@tatiana I am guessing Constance is referring to add that to our [public Cosmos docs](https://astronomer.github.io/astronomer-cosmos/), too? Just a guess :).

And if the above guess is correct, @cmarteepants, although the current change in the PR suffices for our GitHub README.md, if we would also like to introduce that to our [public Cosmos docs](https://astronomer.github.io/astronomer-cosmos/), you would need to introduce the same changes in [docs](https://github.com/astronomer/astronomer-cosmos/tree/main/docs) folder which is what the `hatch run docs:serve` refers to (and hence also Netlify). Probably, you could add the same in https://github.com/astronomer/astronomer-cosmos/blob/main/docs/index.rst for hatch/Netlify to detect changes & also reflect on our Cosmos public docs.

**Comment by tatiana** [comment]
Very true, @pankajkoti ! It would be great if we removed this redundancy between `README.md` and `index.rst` - but this may be part of the general improve the docs ticket. I remember Constance mentioning she wanted us to improve the overall docs, so I just logged a ticket so we don't lose track of these: https://github.com/astronomer/astronomer-cosmos/issues/new

**Comment by cmarteepants** [comment]
Thanks for the information, I'll add it there and submit the commit

**Pull request merged**
